### ISSUE TITLE
Ability to load preferred files at first (like Angular, jQuery...)

### ISSUE THREAD

**Issue by orafaelfragoso** [lbragaglia/karma-wiredep#1]
I need the ability to order the files that are being loaded, because I keep getting errors like:
- jQuery is not defined
- angular is not defined

Because the plugins are loading before the libraries, it's frustrating.

I'll take a look and send a PR as soon as possible, but if you have a workaround for this, please, tell me.

Thanks.

**Comment by lbragaglia** [comment]
Using `wiredep` without `karma` exposes the correct behaviour? If not, it's a `wiredep` issue (or with one of your `bower` deps).

`wiredep` follows dependencies order as specified in `bower.json` and reorder transitive deps accordingly.
You can launch `wiredep` from [command line](https://github.com/taptapship/wiredep-cli) and check the order of js file found (see the trailing rows of the output):
`node_modules/.bin/wiredep -s nofile --verbose`
(or simply `wiredep -s nofile --verbose` if installed globally).

It seems to me a wrong or incomplete "main" attribute in `bower.json` of some of your dependencies. As a workaround you may use [bower overrides](https://github.com/taptapship/wiredep#bower-overrides) that is honored by `wiredep`.

Please post a snippet of your config and log/error if you need more advice.
